version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - ./frontend:/app

  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stock_manager
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: